### ISSUE TITLE
Permission denied: '/usr/local/tests'

### ISSUE THREAD

**Issue by daducci** [getspams/spams-python#10] opened 2022-03-05 14:39 UTC
Hi guys,
while installing SPAMS (`pip install spams`, I get the following error:

> ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/tests'
> Consider using the `--user` option or check the permissions.

I know I can use the PIP option `--user`, but this happens only for SPAMS and, what is really weird, is that if I run twice `pip install spams`, I get the error only the first time, the second one no error shows up.

I am not very familiar with the build system; any clue?

**Comment by samuelstjean** [comment] 2022-03-07 08:23
Might be caused by the setup.py trying to install the doc, I remember I axes that part. Since the manifest already puts them in the zip, I guess that part could be deleted, since absolutely no one will go look for the doc inside system folders (and it's in the zip, it just will not get installed).

**Comment by gdurif** [comment] 2022-03-07 16:46
I'll look into the doc setup (and remove the copy at install which is indeed useless).

**Comment by gdurif** [comment] 2022-03-07 17:21
The doc issue should be fixed by #14 

@daducci could you tell me if `pip install git+https://github.com/getspams/spams-python.git@remove_doc_copy` works for you?

**Comment by daducci** [comment] 2022-03-08 07:40
No, it doesn't, I still get the error:
```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/tests'
Consider using the `--user` option or check the permissions.
```

**Comment by gdurif** [comment] 2022-03-08 08:39
@daducci could you give more details on the environment (OS, Python version, etc.) on which you are encountering this issue ?

And if you try installing previous version from PyPI like `pip install spams==2.6.3.3` ([here](https://pypi.org/project/spams/#history) is the history of version available on PyPI), all fail or some can be installed ?

Thanks

**Comment by daducci** [comment] 2022-03-08 09:38
I'm on the new Macbook M1 with OSX 12.2.1 (Monterey) and python 3.9.10 (installed via `howebrew`), and this error happens with all `spams` versions. Whats is weird is that the first time I run `pip install spams` I get this error (and, in turn, our `dmri-amico` package is not installed), whereas if I run `pip install spams` a second time, the installation runs fine and also `dmri-amico` is properly installed without any error. Weird and I don't know why this happens...

**Comment by gdurif** [comment] 2022-03-08 09:41
Do you have an example of a package that you can install without any issue (beside `spams` or `dmri-amico`)?

**Comment by daducci** [comment] 2022-03-08 10:33
I install all other packages, e.g. `numpy`, `scipy`, `nibabel`, `networkx` etc, via `pip install <name>` (i.e., without flag `--user`) and they are installed properly. May this be due to a different settings which installs the `tests` in a wrong folder?

**Comment by gdurif** [comment] 2022-03-08 13:15
Is `pip install spams-bin` working ?

**Comment by daducci** [comment] 2022-03-08 13:53
Yes, indeed it does, without that error! :-)

**Comment by gdurif** [comment] 2022-03-08 13:55
Ok, I think I understand the problem. Package with pre-built wheels do not cause any problem, but when you need some local build from source, it causes the issue.

**Comment by samuelstjean** [comment] 2022-03-08 14:15
any modern local install should try to make wheels and install that, so I'd still point the culprit to the rest of the doc and test folder from the setup.py part. I'd guess the setup tries to install the files somehow (just like with the data folder) for important stuff, while the manifest only puts them in the source zip and discards everything from the real build.

Assuming nobody would ever read or run tests from the installed files and that we only want them in the zip (since people can easily refer to those instead), then this would be doable by removing all of those references from the setup.py and only using the manifest.in file. More details here https://packaging.python.org/en/latest/guides/using-manifest-in/

If you want to put here the wheel files before install (probably under /dist in your local folder), they likely contains references to those doc and tests files.

**Comment by gdurif** [comment] 2022-03-08 15:25
Potentially fixed by #15 

Does `pip install git+https://github.com/getspams/spams-python.git@fix_pkg_data_install` work now?

**Comment by daducci** [comment] 2022-03-08 16:09
Yes, it does! Is there a way, though, to keep the test files in case a user want to run the tests?

**Comment by gdurif** [comment] 2022-03-08 17:05
Reading more carefully the explanation of Samuel and the related link to `setuptools` doc, it should be possible, I'll do the change tomorrow.

**Comment by daducci** [comment] 2022-03-08 19:46
Thanks Ghislain!

**Comment by daducci** [comment] 2022-03-09 09:19
By the way, did you try installing the extra files (e.g. tests) by changing the keyword `data_files` to `package_data` in `setup.py`?  It seems that:

- `package_data` - defines files related to the python package. eg. documentation, static image files, configurations.
- `data_files` - defines files that will be installed system-wise, not in site-package directory. eg. desktop icons, fonts.

Perhaps, this might be a workaround.

**Comment by gdurif** [comment] 2022-03-09 10:57
@daducci I did that :smiley: 

Could you tell me if `pip install git+https://github.com/getspams/spams-python.git@fix_pkg_data_install` still works?

Besides, I added a new way to call the tests from Python, for people installing the package from PyPI and wanting to tests the package without cloning the repository or download the distribution file from PyPI (c.f. [here](https://github.com/getspams/spams-python/blob/fix_pkg_data_install/README.md#testing-the-interface)).

**Comment by daducci** [comment] 2022-03-09 12:04
Ops, I hadn't checked the code, simply installed it via pip! :-P

This new version (previous comment) still works.

**Comment by gdurif** [comment] 2022-03-09 13:26
Great, I am merging #15 and closing this :smiley:

**Closed by gdurif** 2022-03-09 13:26 UTC
